name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f61b826881fca5fd3ff2cb0f0da974e2ac82d644965f39b762ba20353403c2ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
