name = "Craft Nectar Network"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2a62eb251d587b7f68f54433cbb4422116cce1d30cbc1623cec1e53b02f6e1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
