name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6608484ad0ac61e9e686bba8b31b97eff3426bf2339d2e503b74f63bdbc85a15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
