name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48ab3ab5e7f8b9790b706383f6031673841380cfaf6fed91d240242e091b0b3d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
