name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "132f1824e95914ab7edaf005dd4f61b811fd9ef817e09134ea03da67e747f38e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
