name = "Craft Nectar Network"
author = "Sewdohe"
version = "4.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "139d1f24e68df9d4fd38fb794fcdbde3caa01a475ce3516611d04ebab8f7cac6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
